# Site settings
title: "van Veen lab"
description: "Hormone signaling in the brain — molecular to systems neuroendocrinology"
url: "https://jevanveen.github.io"
author:
  name: "Ed van Veen"
  email: "[add-your-email]"
  github: "jevanveen"
  scholar: "https://scholar.google.com/citations?user=[your-id]"

# Theme
theme: minima

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Social links (header icons)
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jevanveen" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=[your-id]" }

# Plugins (GitHub Pages–safe)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap