# Site settings
title: "van Veen lab"
description: "molecular and computational neuroendocrinology"
url: "https://jevanveen.github.io"
author:
  name: "Ed van Veen"
  email: "vanveen@ucla.edu"
  github: "jevanveen"
  scholar: "https://scholar.google.com/citations?user=YC4LRXoAAAAJ"

# Theme
theme: minima

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Navigation (used by minima)
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jevanveen" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=[your-id]" }

# Collections
collections:
  pages:
    output: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag